export enum TABS {
  "PM" = "Polícia",
  "BM" = "Bombeiros",
}

export const STATES = [
  { name: "Acre", id: "AC", current: false },
  { name: "Alagoas", id: "AL", current: false },
  { name: "Amapá", id: "AP", current: false },
  { name: "Amazonas", id: "AM", current: false },
  { name: "Bahia", id: "BA", current: false },
  { name: "Ceará", id: "CE", current: false },
  { name: "Distrito Federal", id: "DF", current: false },
  { name: "Espírito Santo", id: "ES", current: false },
  { name: "Goiás", id: "GO", current: false },
  { name: "Maranhão", id: "MA", current: false },
  { name: "Mato Grosso", id: "MT", current: false },
  { name: "Mato Grosso do Sul", id: "MS", current: false },
  { name: "Minas Gerais", id: "MG", current: false },
  { name: "Pará", id: "PA", current: false },
  { name: "Paraíba", id: "PB", current: false },
  { name: "Paraná", id: "PR", current: false },
  { name: "Pernambuco", id: "PE", current: false },
  { name: "Piauí", id: "PI", current: false },
  { name: "Rio de Janeiro", id: "RJ", current: false },
  { name: "Rio Grande do Norte", id: "RN", current: false },
  { name: "Rio Grande do Sul", id: "RS", current: false },
  { name: "Rondônia", id: "RO", current: false },
  { name: "Roraima", id: "RR", current: false },
  { name: "Santa Catarina", id: "SC", current: false },
  { name: "São Paulo", id: "SP", current: false },
  { name: "Sergipe", id: "SE", current: false },
  { name: "Tocantins", id: "TO", current: false },
];
